- name: Restart admission-controller
  ansible.builtin.systemd:
    name: admission-controller
    state: restarted
    daemon_reload: yes
  listen: restart admission-controller

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes