tdx_repo: "{{ repo_root }}/tdx"
charts_dir: "{{ repo_root }}/charts"
logfile: "{{ repo_root }}/tdx-image-build.log"
vnc_port: "5901"
cloud_init_dir: "{{ repo_root }}/local"
user_data_file: "{{ cloud_init_dir }}/user-data"
no_cache: "{{ lookup('env', 'NO_CACHE') | default('false', true) | lower }}"
debug: "{{ lookup('env', 'DEBUG') | default('false', true) | lower }}"
ssh_public_key_path: "~/.ssh/id_rsa.pub"
ssh_private_key_path: "~/.ssh/id_rsa"
build_vm_ram: 8192
build_vm_vcpus: 4
build_vm_mac: "52:54:00:60:a6:0a"
build_vm_network: "sek8s-build"
build_vm_network_bridge: "virbr-sek8s"
build_vm_network_candidates:
  - gateway: "192.168.122.1"
    netmask: "255.255.255.0"
    dhcp_start: "192.168.122.100"
    dhcp_end: "192.168.122.200"
    vm_ip: "192.168.122.176"
  - gateway: "10.122.0.1"
    netmask: "255.255.255.0"
    dhcp_start: "10.122.0.100"
    dhcp_end: "10.122.0.200"
    vm_ip: "10.122.0.176"