tdx_repo: "{{ repo_root }}/tdx"
charts_dir: "{{ repo_root }}/charts"
logfile: "{{ repo_root }}/tdx-image-build.log"
vnc_port: "5901"
cloud_init_dir: "{{ repo_root }}/local"
user_data_file: "{{ cloud_init_dir }}/user-data"
no_cache: "{{ lookup('env', 'NO_CACHE') | default('false', true) | lower }}"
debug: "{{ lookup('env', 'DEBUG') | default('false', true) | lower }}"
ssh_public_key_path: "~/.ssh/id_rsa.pub"
ssh_private_key_path: "~/.ssh/id_rsa"