repo_root: "{{ playbook_dir }}/../../.."
ubuntu_version: "25.04"
img_dir: "{{ repo_root }}/guest-tools/image"
cosign_key_path: "{{ ansible_env.HOME }}/.cosign/cosign.pub"
sek8s_img_path: "{{ img_dir }}/tdx-guest-ubuntu-{{ ubuntu_version }}.qcow2"
final_img_path: "{{ img_dir }}/tdx-guest-ubuntu-{{ ubuntu_version }}-final.qcow2"
vm_name: "tdx-build"