repo_root: "{{ playbook_dir }}/../../.."
ubuntu_version: "24.04"
img_dir: "{{ repo_root }}/guest-tools/image"
base_img_path: "{{ img_dir }}/tdx-guest-ubuntu-{{ ubuntu_version }}.qcow2"
libvirt_image_dir: "/var/lib/libvirt/images"
build_img_path: "{{ libvirt_image_dir }}/tdx-guest.qcow2"
vm_name: "tdx-build"