---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BlockPodExec
metadata:
  name: block-pod-exec
  labels:
    gatekeeper.sh/system: "yes"
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-system", "gatekeeper-system", "kube-public", "kube-node-lease"]
  parameters:
    exemptNamespaces: 
      - "kube-system"
      - "gatekeeper-system" 
      - "kube-public"
      - "kube-node-lease"
    exemptImages: []