---
- name: Install k3s
  ansible.builtin.include_tasks: install.yml
  tags: k3s-install

- name: Setup node
  ansible.builtin.include_tasks: setup_node.yml
  tags: k3s-node
  
- name: Setup config init service
  ansible.builtin.include_tasks: setup_config_init.yml
  tags: k3s-config-init

- name: Setup cluster init service
  ansible.builtin.include_tasks: setup_cluster_init.yml
  tags: k3s-cluster-init