---
# inventory.yml
all:
  children:
    vm:
      hosts: # Dynamically populated by playbook
    host:
      hosts:
        localhost:
          ansible_connection: local

  vars:
    ansible_user: "{{ lookup('env', 'USER') }}"
    cosign_public_key_path: "~/.cosign/cosign.pub"
    luks_passphrase: "{{ lookup('env', 'LUKS_PASSPHRASE') | mandatory }}"