---
- name: Cleanup k3s
  ansible.builtin.include_tasks: cleanup-k3s.yml
  when: inventory_hostname in groups['vm']

- name: Include k3s drop-ins
  ansible.builtin.include_tasks: k3s-drop-ins.yml
  when: inventory_hostname in groups['vm']

- name: Cleanup attestation service
  ansible.builtin.include_tasks: cleanup-attestation-service.yml
  when: inventory_hostname in groups['vm']

- name: Cleanup GPU verification service
  ansible.builtin.include_tasks: cleanup-gpu-verify-service.yml
  when: inventory_hostname in groups['vm']

- name: Cleanup cloud-init
  ansible.builtin.include_tasks: cleanup-cloud-init.yml
  when: inventory_hostname in groups['vm']

- name: Cleanup system
  ansible.builtin.include_tasks: cleanup-build.yml
  when: inventory_hostname in groups['vm']

- name: Cleanup VM
  ansible.builtin.include_tasks: cleanup-vm.yml
  when: inventory_hostname in groups['host']
  